version: '3'
services:
  app:
    build: .
    container_name: my_rent_app
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URL=mongodb+srv://xolmominovj2023:zOxBc4iI4T27cH2z@cluster0.r2hvz7t.mongodb.net/Myrent
      - JWT_SECRET=Myrent
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CACHE_TIMEOUT=3600
    networks:
      - proxynet
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: my_redis
    ports:
      - "6379:6379"
    networks:
      - proxynet

networks:
  proxynet: